spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: invoice_report
      authentication-database: admin
      username: gburich
      password: gburich

report:
  template-path: /report/invoice_report.jrxml
  name-prefix: invoice